version: "3.9"
services:
  maven: 
    build: ./maven-build
    container_name: maven-build
    volumes:
      - mydata:/target/

  tomcat:
    image: davidcaste/alpine-tomcat:tomcat8
    container_name: tomcat
    depends_on:
      - maven
    ports:
      - target: 8080
        published: 8888
        protocol: tcp
    volumes:
      - ./target/hello-1.0.war:/usr/local/tomcat/webapps/hello-1.0.war
    command: /opt/tomcat/bin/catalina.sh run

volumes:
  mydata:

